### ISSUE TITLE
[Ubuntu 22.04] Error on test printing 

### ISSUE THREAD

**Issue by quentinDupont** [akretion/pywebdriver#133]
Works in Odoo but not in test
In log, here is the error when we test print :

`
mai 05 14:10:21 dtbnew-DH310S pywebdriverd[18469]: ERROR:pywebdriver:not well-formed (invalid token): line 6, column 42
mai 05 14:10:21 dtbnew-DH310S pywebdriverd[18469]: ------------------------------------------------------------
mai 05 14:10:21 dtbnew-DH310S pywebdriverd[18469]: Traceback (most recent call last):
mai 05 14:10:21 dtbnew-DH310S pywebdriverd[18469]:   File "/opt/venvs/pywebdriver/lib/python3.10/site-packages/pywebdriver/plugins/base_driver.py", line 107, in run
mai 05 14:10:21 dtbnew-DH310S pywebdriverd[18469]:     self.process_task(task, timestamp, data)
mai 05 14:10:21 dtbnew-DH310S pywebdriverd[18469]:   File "/opt/venvs/pywebdriver/lib/python3.10/site-packages/pywebdriver/plugins/base_driver.py", line 95, in process_task
mai 05 14:10:21 dtbnew-DH310S pywebdriverd[18469]:     return getattr(self, task)(data)
mai 05 14:10:21 dtbnew-DH310S pywebdriverd[18469]:   File "/opt/venvs/pywebdriver/lib/python3.10/site-packages/pywebdriver/plugins/escpos_driver.py", line 351, in printstatus
mai 05 14:10:21 dtbnew-DH310S pywebdriverd[18469]:     Layout("<div>" + msg + "</div>").format(self)
mai 05 14:10:21 dtbnew-DH310S pywebdriverd[18469]:   File "/opt/venvs/pywebdriver/lib/python3.10/site-packages/xmlescpos/layout.py", line 337, in __init__
mai 05 14:10:21 dtbnew-DH310S pywebdriverd[18469]:     self._root = root = ET.fromstring(xml.encode('utf-8'))
mai 05 14:10:21 dtbnew-DH310S pywebdriverd[18469]:   File "/usr/lib/python3.10/xml/etree/ElementTree.py", line 1342, in XML
mai 05 14:10:21 dtbnew-DH310S pywebdriverd[18469]:     parser.feed(text)
mai 05 14:10:21 dtbnew-DH310S pywebdriverd[18469]: xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 6, column 42
mai 05 14:10:21 dtbnew-DH310S pywebdriverd[18469]: ------------------------------------------------------------
`

**Comment by quentinDupont** [comment]
It just happened on a second computer also on Ubuntu 22.04 (former Ubuntu 20.04 that was upgraded)
