### ISSUE TITLE
Printer not connecting 

### ISSUE THREAD

**Issue by fawyna** [akretion/pywebdriver#15]
We are using this thermal printer, TC-5890T THERMAL PRINTER: http://www.tcang.net/products?ID=6

This printer works with PosBox-less setup for Odoo 8 and 9 on Ubuntu 14.04 and 15.10. But not able to connect and print with pywebdriver on Ubuntu 14.04.3 running in VirtualBox.

Error is as shown below:

![escpos](https://cloud.githubusercontent.com/assets/14052188/12014014/8260d7a2-ad5e-11e5-880a-226cea72c4c7.JPG)

Sometimes it is **Input/Output error** instead.

`dmesg` returns: 
```
...
[12635.729583] usb 2-2: usbfs: interface 0 claimed by usbfs while 'python' sets config #1
[12640.785735] usb 2-2: usbfs: interface 0 claimed by usbfs while 'python' sets config #1
[12645.828507] usb 2-2: usbfs: interface 0 claimed by usbfs while 'python' sets config #1
[12650.879539] usb 2-2: usbfs: interface 0 claimed by usbfs while 'python' sets config #1
...
```

We have tried: 

1) adding the printer to `device_list`
2) changing escpos_driver to find usb.core.find. Which it did find, but it was still throwing resource busy. 

We checked the logs:

```
--------------------------------------------------------------------------------
ERROR in base_driver [/usr/lib/python2.7/dist-packages/pywebdriver/plugins/base_driver.py:110]:
[Errno 110] Operation timed out
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pywebdriver/plugins/base_driver.py", line 105, in run
    self.process_task(task, timestamp, data)
  File "/usr/lib/python2.7/dist-packages/pywebdriver/plugins/base_driver.py", line 92, in process_task
    return getattr(self, task)(data)
  File "/usr/lib/python2.7/dist-packages/pywebdriver/plugins/escpos_driver.py", line 135, in printstatus
    self.receipt('<div>'+msg+'</div>')
  File "/usr/local/lib/python2.7/dist-packages/xmlescpos/escpos.py", line 757, in receipt
    self.text(errmsg)
  File "/usr/local/lib/python2.7/dist-packages/xmlescpos/escpos.py", line 872, in text
    self._raw(txt)
  File "/usr/local/lib/python2.7/dist-packages/xmlescpos/printer.py", line 68, in _raw
    if len(msg) != self.device.write(self.out_ep, msg, self.interface):
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 878, in write
    self.__get_timeout(timeout)
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 760, in bulk_write
    timeout)
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 856, in __write
    _check(retval)
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 552, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
USBError: [Errno 110] Operation timed out
------------------------------------------------------------

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
ERROR in base_driver [/usr/lib/python2.7/dist-packages/pywebdriver/plugins/base_driver.py:110]:
[Errno 16] Resource busy
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pywebdriver/plugins/base_driver.py", line 105, in run
    self.process_task(task, timestamp, data)
  File "/usr/lib/python2.7/dist-packages/pywebdriver/plugins/base_driver.py", line 92, in process_task
    return getattr(self, task)(data)
  File "/usr/lib/python2.7/dist-packages/pywebdriver/plugins/escpos_driver.py", line 158, in printstatus
    self.receipt(msg)
  File "/usr/local/lib/python2.7/dist-packages/xmlescpos/escpos.py", line 757, in receipt
    self.text(errmsg)
  File "/usr/local/lib/python2.7/dist-packages/xmlescpos/escpos.py", line 872, in text
    self._raw(txt)
  File "/usr/local/lib/python2.7/dist-packages/xmlescpos/printer.py", line 68, in _raw
    if len(msg) != self.device.write(self.out_ep, msg, self.interface):
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 870, in write
    intf, ep = self._ctx.setup_request(self, endpoint)
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 190, in setup_request
    self.managed_claim_interface(device, intf)
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 146, in managed_claim_interface
    self.backend.claim_interface(self.handle, i)
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 747, in claim_interface
    _check(self.lib.libusb_claim_interface(dev_handle.handle, intf))
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 552, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
USBError: [Errno 16] Resource busy
------------------------------------------------------------

--------------------------------------------------------------------------------
```

What do I do to make it work?

**Comment by fawyna** [comment]
Oh yes, I also set the config.ini to print when connected. 

```
print_status_start=true
```

Every time I start the VirtualBox instance, it prints. however, it prints an error. The error: 

![img_20151228_141948](https://cloud.githubusercontent.com/assets/14052188/12014861/967b0946-ad6e-11e5-87cb-1c8469215c06.JPG)

**Comment by legalsylvain** [comment]
Sorry I did not received issues by email. This error is due to insufficient access right to the printer. I think it has been fixed with last pywebdriver release. If not tell me.
