### ISSUE TITLE
Resource Busy Error with Epson TM20III

### ISSUE THREAD

**Issue by nwinkelstraeter** [akretion/pywebdriver#96]
Hello,

I'm running into this error sporadically and i haven't identified a pattern to when the errors occur.
Printing the status page works fine and after printing a couple of receipts this error occurs.

This problem occurs on a Raspberry PI 4 as well as an ordinary x86 Laptop.
dmesg also shows the following message repeatedly once the error occurs:
```
 usbfs: interface 0 claimed by usbfs while 'pywebdriverd' sets config #1
```

Any pointers as to what could be causing this issue would be greatly appreciated.

Printer Device: Epson TM20III
Configuration:
```
...
[escpos_driver]
device_type=usb
...
```

Note: I`m using the code from #95 but I don't think that matters as those changes are unrelated to the escpos driver

```
Traceback (most recent call last):
  File "/opt/venvs/pywebdriver/lib/python3.8/site-packages/pywebdriver/plugins/base_driver.py", line 107, in run
    self.process_task(task, timestamp, data)
  File "/opt/venvs/pywebdriver/lib/python3.8/site-packages/pywebdriver/plugins/base_driver.py", line 95, in process_task
    return getattr(self, task)(data)
  File "/opt/venvs/pywebdriver/lib/python3.8/site-packages/pywebdriver/plugins/escpos_driver.py", line 294, in receipt_jpeg
    self.receipt(content)
  File "/opt/venvs/pywebdriver/lib/python3.8/site-packages/pywebdriver/plugins/escpos_driver.py", line 298, in receipt
    Layout(content).format(self)
  File "/opt/venvs/pywebdriver/lib/python3.8/site-packages/xmlescpos/layout.py", line 563, in format
    printer._raw(SHEET_ROLL_MODE)
  File "/opt/venvs/pywebdriver/lib/python3.8/site-packages/escpos/printer.py", line 100, in _raw
    self.device.write(self.out_ep, msg, self.timeout)
  File "/opt/venvs/pywebdriver/lib/python3.8/site-packages/usb/core.py", line 986, in write
    intf, ep = self._ctx.setup_request(self, endpoint)
  File "/opt/venvs/pywebdriver/lib/python3.8/site-packages/usb/core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/venvs/pywebdriver/lib/python3.8/site-packages/usb/core.py", line 229, in setup_request
    self.managed_claim_interface(device, intf)
  File "/opt/venvs/pywebdriver/lib/python3.8/site-packages/usb/core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/venvs/pywebdriver/lib/python3.8/site-packages/usb/core.py", line 178, in managed_claim_interface
    self.backend.claim_interface(self.handle, i)
  File "/opt/venvs/pywebdriver/lib/python3.8/site-packages/usb/backend/libusb1.py", line 829, in claim_interface
    _check(self.lib.libusb_claim_interface(dev_handle.handle, intf))
  File "/opt/venvs/pywebdriver/lib/python3.8/site-packages/usb/backend/libusb1.py", line 604, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 16] Resource busy
```

**Comment by OSevangelist** [comment]
Did anyone at Akretion encounter similar problems wirth stability @sebastienbeau, @PierrickBrun @rvalyi ?

**Comment by legalsylvain** [comment]
Hi. i deploy pywebdriver on many point of sale in my company. (GRAP) pywebdriver is installed on ~50 computers. (Ubuntu 16/18 or 20) and in all the point of sale, there are an epson tmt ii or iii.

sometimes, users has to restart the pywebdriver service. (once a day, to once a month).

I didn't investigate deeply, but maybe that is the origin of the error.

if you have some patch to propose, I can test it in some shops, to see if it fix the problem.

kind regards.

**Comment by legalsylvain** [comment]
CC @quentinDupont FYI.

**Comment by PierrickBrun** [comment]
I did not know about this problem. I do not think this is something that happens in the pos we deploy.

**Comment by OSevangelist** [comment]
Hi @legalsylvain @PierrickBrun this is weird. At our end it happened much more often during the tests lately, but my colleagues @fkantelberg and @nwinkelstraeter will give it another round of debugging tomorrow. 

What we want to try is changing the code a bit so that it doesn't re-initiate the connection to the printer every time a receipt is printed but just in case the printer isn't reachable using the pywebdriver functions any longer. The second angle of attack would be to create a specific udev rule that blocks the kernel driver from exclusively blocking the resource for itself as this seems to evoke the problem (root cause is not yet clear whatsoever)

**Comment by legalsylvain** [comment]
> I did not know about this problem. I do not think this is something that happens in the pos we deploy.

You deploy on windows, right ?

**Comment by OSevangelist** [comment]
No @legalsylvain we don't work with Windows

**Comment by legalsylvain** [comment]
> No @legalsylvain we don't work with Windows

the question was for @PierrickBrun.

**Comment by OSevangelist** [comment]
@legalsylvain ah sorry ok

**Comment by PierrickBrun** [comment]
> > I did not know about this problem. I do not think this is something that happens in the pos we deploy.
> 
> You deploy on windows, right ?

Most of the time yes, but we have some linux installs also

**Comment by OSevangelist** [comment]
well let's see what our debugging session tomorrow will provide us. If we could simply circumvent the issues by adding a udev rule so be it and we will provide appropriate patches thenafter. Thanks for your help so far

**Comment by nwinkelstraeter** [comment]
We believe that the problem occurred because of frequent re-opening of the usb Device. This happens because the device is closed on every status request.
Removing this fixed the issue for us. See https://github.com/initOS/pywebdriver/commits/fix-printer-reconnect

Also the is_online() call adds a 1s delay to the status request, which is also the timeout pos_payment_terminal sets to determine a broken connection, which caused problems when using a payment terminal and an escpos printer.

**Comment by TheCloneMaster** [comment]
We faced stability problems too on Ubuntu 20.04 with direct usb connection.  Will try @nwinkelstraeter  fix and report back...

**Comment by legalsylvain** [comment]
Hi @paragasu. Did you planned to propose a PR of your commit ? [c575bef](https://github.com/paragasu/pywebdriver/commit/c575bef30e250fc341e5c5e8bb090e13899199f0)

thanks !

**Comment by huguesdk** [comment]
i’ve been experiencing the same kind of errors with an epson tm-t20ii on ubuntu 22.04 and python 3.10.12. at first, i thought it was due to the fact that the printer was configured in cups. i’ve removed the printer from cups (`lpadmin -x EPSON-TM-T20II`), but the problem remained.

there are several types of errors (reported by `/status_json`):

1.  `{"escpos":{"messages":["Error: [Errno 16] Resource busy"],"status":"error"}}`
2.  `{"escpos":{"messages":[],"status":"disconnected"}}`
3.  `{"escpos":{"messages":["Error: 'NoneType' object has no attribute 'read'"],"status":"error"}}`

`Could not set configuration: [Errno 16] Resource busy` also appears sometimes repeatedly in the log.

i tried downgrading `pyusb` from 1.2.1 to 1.0.2 as suggested in #88, but it does not seem to change anything.
